shopdb.brand/id INTEGER PRIMARY KEY AUTOINCREMENT,nameBrand STRING  NOT NULL UNIQUE
shopdb.category/id INTEGER PRIMARY KEY AUTOINCREMENT,nameCategory STRING  NOT NULL UNIQUE,discount INTEGER NOT NULL,aliasName STRING
shopdb.type/id INTEGER PRIMARY KEY AUTOINCREMENT,nameType STRING  NOT NULL UNIQUE
shopdb.product/id INTEGER PRIMARY KEY AUTOINCREMENT,brandId INTEGER REFERENCES shopdb.brand (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,categoryId INTEGER REFERENCES shopdb.category (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,typeId INTEGER REFERENCES shopdb.type (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,price REAL NOT NULL
shopdb.order/id INTEGER PRIMARY KEY AUTOINCREMENT,userName STRING  NOT NULL UNIQUE,phone STRING NOT NULL
shopdb.orderProducts/productId INTEGER REFERENCES shopdb.product (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,orderId INTEGER REFERENCES shopdb.order (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,count INTEGER,CONSTRAINT new_pk PRIMARY KEY(productId, orderId)
shopdb.students/id INTEGER PRIMARY KEY AUTOINCREMENT,name STRING  NOT NULL UNIQUE