brand/id INTEGER PRIMARY KEY AUTOINCREMENT, nameBrand STRING  NOT NULL UNIQUE
category/id INTEGER PRIMARY KEY AUTOINCREMENT, nameCategory STRING  NOT NULL UNIQUE, discount INTEGER NOT NULL, aliasName STRING
type/id INTEGER PRIMARY KEY AUTOINCREMENT, nameType STRING NOT NULL UNIQUE
orders/id INTEGER PRIMARY KEY AUTOINCREMENT, userName STRING NOT NULL UNIQUE, phone STRING NOT NULL
product/id INTEGER PRIMARY KEY AUTOINCREMENT, brandId INTEGER REFERENCES brand (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, categoryId INTEGER REFERENCES category (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, typeId INTEGER REFERENCES type (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, price REAL NOT NULL
ordersProducts/productId INTEGER REFERENCES product (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, ordersId INTEGER REFERENCES orders (id) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, count INTEGER,CONSTRAINT new_pk PRIMARY KEY(productId, ordersId)
students/id INTEGER PRIMARY KEY AUTOINCREMENT, name STRING  NOT NULL UNIQUE